# Variables de entorno del proveedor de Correo electrónic
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
      APIKEY_BREVO: ${APIKEY_BREVO}
      URL_BREVO: ${URL_BREVO}
    ports:
      - 3000:3000
    env_file:
      - .env

