# Variables de entorno del proveedor de Correo electrónic
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      APIKEY_BREVO: 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
      URL_BREVO: https://api.brevo.com/v3/smtp/email
    ports:
      - 3000:3000

